import type { ComplianceTemplateDefinition } from "./types";

/**
 * Industry starter templates — seeded as public ReportTemplates (purpose=compliance).
 * Keys are stable; templateName must remain unique in report-templates.
 */
export const INDUSTRY_STARTERS: ComplianceTemplateDefinition[] = [
  {
    starterKey: "oil_gas",
    templateName: "ClearESG Oil & Gas Compliance",
    description:
      "Upstream/downstream GHG, methane, flaring, and intensity for oil & gas operators.",
    industry: "oil_gas",
    framework: "sasb",
    sections: [
      {
        sectionTitle: "Operations",
        sectionKey: "operations",
        sectionType: "questions",
        order: 1,
      },
      {
        sectionTitle: "Methane & flaring",
        sectionKey: "methane",
        sectionType: "questions",
        order: 2,
      },
      {
        sectionTitle: "Intensity",
        sectionKey: "intensity",
        sectionType: "calculations",
        order: 3,
      },
    ],
    questions: [
      {
        questionId: "og-scope1",
        sectionKey: "operations",
        label: "Scope 1 total",
        prompt: "Report Scope 1 GHG emissions for the assessment year (tCO₂e).",
        answerType: "number",
        unit: "tCO₂e",
        required: true,
        order: 1,
      },
      {
        questionId: "og-scope2",
        sectionKey: "operations",
        label: "Scope 2 total",
        prompt: "Report Scope 2 GHG emissions (location- or market-based) (tCO₂e).",
        answerType: "number",
        unit: "tCO₂e",
        required: true,
        order: 2,
      },
      {
        questionId: "og-production",
        sectionKey: "operations",
        label: "Hydrocarbon production",
        prompt: "Net hydrocarbon production for the year (boe).",
        answerType: "number",
        unit: "boe",
        required: true,
        order: 3,
      },
      {
        questionId: "og-methane",
        sectionKey: "methane",
        label: "Methane emissions",
        prompt: "Estimate methane emissions converted to CO₂e (tCO₂e).",
        answerType: "number",
        unit: "tCO₂e",
        required: true,
        order: 1,
      },
      {
        questionId: "og-flaring",
        sectionKey: "methane",
        label: "Flaring volume",
        prompt: "Volume of gas flared (mscm).",
        answerType: "number",
        unit: "mscm",
        required: false,
        order: 2,
      },
      {
        questionId: "og-ldar",
        sectionKey: "methane",
        label: "LDAR programme",
        prompt: "Describe leak detection and repair coverage this year.",
        answerType: "text",
        required: true,
        order: 3,
      },
    ],
    calculations: [
      {
        calcId: "og-ops-total",
        label: "Operational Scope 1+2",
        op: "sum",
        inputs: ["og-scope1", "og-scope2"],
        unit: "tCO₂e",
        sectionKey: "intensity",
      },
      {
        calcId: "og-intensity",
        label: "Emissions intensity",
        op: "ratio",
        inputs: ["og-ops-total", "og-production"],
        unit: "tCO₂e / boe",
        sectionKey: "intensity",
      },
    ],
  },
  {
    starterKey: "manufacturing",
    templateName: "ClearESG Manufacturing Compliance",
    description: "Process energy, scrap, and product intensity for manufacturing sites.",
    industry: "manufacturing",
    framework: "gri",
    sections: [
      {
        sectionTitle: "Energy & process",
        sectionKey: "energy",
        sectionType: "questions",
        order: 1,
      },
      {
        sectionTitle: "Material efficiency",
        sectionKey: "materials",
        sectionType: "questions",
        order: 2,
      },
      {
        sectionTitle: "Derived metrics",
        sectionKey: "derived",
        sectionType: "calculations",
        order: 3,
      },
    ],
    questions: [
      {
        questionId: "mfg-electricity",
        sectionKey: "energy",
        label: "Purchased electricity",
        prompt: "Electricity consumed (MWh).",
        answerType: "number",
        unit: "MWh",
        required: true,
        order: 1,
      },
      {
        questionId: "mfg-fuel",
        sectionKey: "energy",
        label: "On-site fuel",
        prompt: "On-site fuel energy (MWh equivalent).",
        answerType: "number",
        unit: "MWh",
        required: true,
        order: 2,
      },
      {
        questionId: "mfg-process",
        sectionKey: "energy",
        label: "Process emissions",
        prompt: "Process GHG emissions (tCO₂e).",
        answerType: "number",
        unit: "tCO₂e",
        required: true,
        order: 3,
      },
      {
        questionId: "mfg-output",
        sectionKey: "materials",
        label: "Finished goods output",
        prompt: "Units of finished product shipped.",
        answerType: "number",
        unit: "units",
        required: true,
        order: 1,
      },
      {
        questionId: "mfg-scrap",
        sectionKey: "materials",
        label: "Scrap / rework rate",
        prompt: "Scrap or rework as percent of input mass.",
        answerType: "number",
        unit: "%",
        required: false,
        order: 2,
      },
      {
        questionId: "mfg-controls",
        sectionKey: "materials",
        label: "Abatement controls",
        prompt: "Describe process abatement or energy-efficiency controls in place.",
        answerType: "text",
        required: true,
        order: 3,
      },
    ],
    calculations: [
      {
        calcId: "mfg-energy-total",
        label: "Total site energy",
        op: "sum",
        inputs: ["mfg-electricity", "mfg-fuel"],
        unit: "MWh",
        sectionKey: "derived",
      },
      {
        calcId: "mfg-energy-intensity",
        label: "Energy intensity",
        op: "ratio",
        inputs: ["mfg-energy-total", "mfg-output"],
        unit: "MWh / unit",
        sectionKey: "derived",
      },
    ],
  },
  {
    starterKey: "finance",
    templateName: "ClearESG Finance Compliance",
    description:
      "Financed emissions coverage, exclusions, and portfolio intensity for financial institutions.",
    industry: "finance",
    framework: "custom",
    sections: [
      {
        sectionTitle: "Portfolio",
        sectionKey: "portfolio",
        sectionType: "questions",
        order: 1,
      },
      {
        sectionTitle: "Governance",
        sectionKey: "governance",
        sectionType: "questions",
        order: 2,
      },
      {
        sectionTitle: "Coverage metrics",
        sectionKey: "coverage",
        sectionType: "calculations",
        order: 3,
      },
    ],
    questions: [
      {
        questionId: "fin-aum",
        sectionKey: "portfolio",
        label: "Assets under management",
        prompt: "Total AUM in scope (million currency units).",
        answerType: "number",
        unit: "mn",
        required: true,
        order: 1,
      },
      {
        questionId: "fin-covered",
        sectionKey: "portfolio",
        label: "AUM with financed emissions",
        prompt: "AUM for which financed emissions are calculated (million).",
        answerType: "number",
        unit: "mn",
        required: true,
        order: 2,
      },
      {
        questionId: "fin-financed",
        sectionKey: "portfolio",
        label: "Financed emissions",
        prompt: "Absolute financed emissions (tCO₂e).",
        answerType: "number",
        unit: "tCO₂e",
        required: true,
        order: 3,
      },
      {
        questionId: "fin-exclusions",
        sectionKey: "governance",
        label: "Sector exclusions",
        prompt: "List climate-related sector exclusions or screens applied.",
        answerType: "text",
        required: true,
        order: 1,
      },
      {
        questionId: "fin-engagement",
        sectionKey: "governance",
        label: "Engagement policy",
        prompt: "Describe engagement with high-emitting counterparties.",
        answerType: "text",
        required: false,
        order: 2,
      },
    ],
    calculations: [
      {
        calcId: "fin-coverage",
        label: "Financed-emissions coverage",
        op: "ratio",
        inputs: ["fin-covered", "fin-aum"],
        unit: "ratio",
        sectionKey: "coverage",
      },
      {
        calcId: "fin-intensity",
        label: "Portfolio intensity",
        op: "ratio",
        inputs: ["fin-financed", "fin-covered"],
        unit: "tCO₂e / mn AUM",
        sectionKey: "coverage",
      },
    ],
  },
  {
    starterKey: "retail",
    templateName: "ClearESG Retail Compliance",
    description:
      "Store energy, logistics, and purchased-goods Scope 3 for retail operators.",
    industry: "retail",
    framework: "gri",
    sections: [
      {
        sectionTitle: "Stores & logistics",
        sectionKey: "ops",
        sectionType: "questions",
        order: 1,
      },
      {
        sectionTitle: "Value chain",
        sectionKey: "value_chain",
        sectionType: "questions",
        order: 2,
      },
      {
        sectionTitle: "Totals",
        sectionKey: "totals",
        sectionType: "calculations",
        order: 3,
      },
    ],
    questions: [
      {
        questionId: "ret-store-energy",
        sectionKey: "ops",
        label: "Store electricity",
        prompt: "Electricity across stores (MWh).",
        answerType: "number",
        unit: "MWh",
        required: true,
        order: 1,
      },
      {
        questionId: "ret-logistics",
        sectionKey: "ops",
        label: "Logistics emissions",
        prompt: "Outbound logistics GHG (tCO₂e).",
        answerType: "number",
        unit: "tCO₂e",
        required: true,
        order: 2,
      },
      {
        questionId: "ret-stores",
        sectionKey: "ops",
        label: "Store count",
        prompt: "Number of stores in reporting boundary.",
        answerType: "number",
        unit: "stores",
        required: true,
        order: 3,
      },
      {
        questionId: "ret-purchased",
        sectionKey: "value_chain",
        label: "Purchased goods (Cat. 1)",
        prompt: "Estimated Scope 3 Category 1 emissions (tCO₂e).",
        answerType: "number",
        unit: "tCO₂e",
        required: true,
        order: 1,
      },
      {
        questionId: "ret-packaging",
        sectionKey: "value_chain",
        label: "Packaging programme",
        prompt: "Describe packaging reduction or recycled-content targets.",
        answerType: "text",
        required: false,
        order: 2,
      },
    ],
    calculations: [
      {
        calcId: "ret-scope3-partial",
        label: "Partial Scope 3 (logistics + purchased goods)",
        op: "sum",
        inputs: ["ret-logistics", "ret-purchased"],
        unit: "tCO₂e",
        sectionKey: "totals",
      },
      {
        calcId: "ret-energy-per-store",
        label: "Electricity per store",
        op: "ratio",
        inputs: ["ret-store-energy", "ret-stores"],
        unit: "MWh / store",
        sectionKey: "totals",
      },
    ],
  },
];
