import { getPayload } from "payload";
import { NextResponse } from "next/server";

import { getCurrentContext, isNextRedirectError } from "@/lib/auth";
import { buildClientInvoiceLineItems, loadClientsUsageRollup } from "@/lib/consultant";
import config from "@/payload.config";

type RouteContext = { params: Promise<{ clientId: string }> };

/**
 * POST /api/app/billing/clients/[clientId]/invoice
 *
 * Draft invoice stub built from the client usage rollup. Requires the client
 * org to already have a Subscription record (Invoices.subscription is
 * required) — when absent, the caller is told to use the CSV export instead
 * rather than the route silently fabricating a subscription.
 */
export async function POST(_req: Request, context: RouteContext) {
  try {
    const ctx = await getCurrentContext();
    if (!ctx.user || !ctx.activeOrg || !ctx.role) {
      return NextResponse.json({ error: "Unauthorized" }, { status: 401 });
    }
    if (ctx.activeOrg.type !== "consultancy") {
      return NextResponse.json(
        { error: "Switch to a consultancy organisation to generate client invoices" },
        { status: 403 },
      );
    }
    if (ctx.role !== "owner" && ctx.role !== "admin") {
      return NextResponse.json(
        { error: "Owner or admin required to generate client invoices" },
        { status: 403 },
      );
    }

    const { clientId } = await context.params;
    const payload = await getPayload({ config });

    const rollup = await loadClientsUsageRollup(
      payload,
      ctx.activeOrg.id,
      ctx.activeOrg.name,
    );
    const client = rollup.clients.find((c) => c.id === clientId);
    if (!client) {
      return NextResponse.json(
        { error: "Client not found under this consultancy" },
        { status: 404 },
      );
    }
    if (
      !client.subscriptionId ||
      !client.currentPeriodStart ||
      !client.currentPeriodEnd
    ) {
      return NextResponse.json(
        {
          error:
            "Client has no subscription record — export the usage CSV instead of generating an invoice.",
        },
        { status: 409 },
      );
    }

    const lineItems = buildClientInvoiceLineItems(client);
    const amount = lineItems.reduce((sum, i) => sum + i.amount, 0);
    const now = new Date();
    const dueDate = new Date(now);
    dueDate.setDate(dueDate.getDate() + 30);
    const invoiceNumber = `CONSULT-${now.getFullYear()}${String(now.getMonth() + 1).padStart(2, "0")}-${client.id.slice(-6).toUpperCase()}-${now.getTime().toString(36).toUpperCase()}`;

    const invoice = await payload.create({
      collection: "invoices",
      data: {
        subscription: client.subscriptionId,
        organisation: client.id,
        invoiceNumber,
        status: "draft",
        periodStart: client.currentPeriodStart,
        periodEnd: client.currentPeriodEnd,
        issueDate: now.toISOString(),
        dueDate: dueDate.toISOString(),
        amount,
        currency: "USD",
        lineItems,
        notes: `Generated by consultancy ${ctx.activeOrg.name} from the client billing rollup. Not sent — review before issuing.`,
      },
      overrideAccess: true,
    });

    return NextResponse.json({ invoice }, { status: 201 });
  } catch (error) {
    if (isNextRedirectError(error)) {
      return NextResponse.json({ error: "Unauthorized" }, { status: 401 });
    }
    console.error("Client invoice generation error:", error);
    return NextResponse.json({ error: "Internal server error" }, { status: 500 });
  }
}
