/**
 * Excel checklist export.
 * RGB fills live at this boundary only — React UI must use CSS tokens.
 * Token mapping (design → spreadsheet):
 *   rust/overdue → B03A2E, amber/due soon → B87309, signal/complete → 0E7C4A
 */

import ExcelJS from "exceljs";

import type { ChecklistExportRow, ChecklistExportSnapshot } from "./checklistExport";

/** Spreadsheet RGB only — mirrored from ClearESG light PDF/print tokens. */
const SHEET = {
  headerBg: "1A1714",
  headerFg: "FBF9F5",
  overdue: "B03A2E",
  dueSoon: "B87309",
  complete: "0E7C4A",
  neutralFg: "1A1714",
  white: "FFFFFF",
} as const;

function statusFill(row: ChecklistExportRow): ExcelJS.Fill | undefined {
  switch (row.urgencyBand) {
    case "overdue":
      return {
        type: "pattern",
        pattern: "solid",
        fgColor: { argb: `FF${SHEET.overdue}` },
      };
    case "due_soon":
      return {
        type: "pattern",
        pattern: "solid",
        fgColor: { argb: `FF${SHEET.dueSoon}` },
      };
    case "complete":
      return {
        type: "pattern",
        pattern: "solid",
        fgColor: { argb: `FF${SHEET.complete}` },
      };
    default:
      return undefined;
  }
}

function statusFontColor(row: ChecklistExportRow): string {
  if (
    row.urgencyBand === "overdue" ||
    row.urgencyBand === "due_soon" ||
    row.urgencyBand === "complete"
  ) {
    return SHEET.white;
  }
  return SHEET.neutralFg;
}

export async function buildChecklistExcelBuffer(
  snapshot: ChecklistExportSnapshot,
): Promise<Buffer> {
  const wb = new ExcelJS.Workbook();
  wb.creator = "ClearESG";
  wb.created = new Date(`${snapshot.exportDate}T00:00:00.000Z`);

  const sheet = wb.addWorksheet("Checklist", {
    views: [{ state: "frozen", ySplit: 1 }],
  });

  sheet.columns = [
    { header: "ID", key: "id", width: 28 },
    { header: "Obligation", key: "obligation", width: 42 },
    { header: "Category", key: "category", width: 14 },
    { header: "Status", key: "status", width: 12 },
    { header: "Due Date", key: "dueDate", width: 14 },
    { header: "Owner", key: "owner", width: 20 },
    { header: "Notes", key: "notes", width: 40 },
    { header: "Evidence Link", key: "evidenceLink", width: 36 },
  ];

  const headerRow = sheet.getRow(1);
  headerRow.font = { bold: true, color: { argb: `FF${SHEET.headerFg}` } };
  headerRow.fill = {
    type: "pattern",
    pattern: "solid",
    fgColor: { argb: `FF${SHEET.headerBg}` },
  };
  headerRow.alignment = { vertical: "middle" };

  for (const row of snapshot.rows) {
    const excelRow = sheet.addRow({
      id: row.id,
      obligation: row.obligation,
      category: row.category,
      status: row.status,
      dueDate: row.dueDate ?? "",
      owner: row.owner,
      notes: row.notes,
      evidenceLink: row.evidenceLink,
    });
    const statusCell = excelRow.getCell("status");
    const fill = statusFill(row);
    if (fill) statusCell.fill = fill;
    statusCell.font = {
      color: { argb: `FF${statusFontColor(row)}` },
      bold: true,
    };
  }

  const lastCol = sheet.columnCount;
  const lastRow = Math.max(sheet.rowCount, 1);
  sheet.autoFilter = {
    from: { row: 1, column: 1 },
    to: { row: lastRow, column: lastCol },
  };

  const summary = wb.addWorksheet("Summary");
  summary.addRow(["Organisation", snapshot.organisationName]);
  summary.addRow(["Export date", snapshot.exportDate]);
  summary.addRow(["Period", snapshot.period]);
  summary.addRow(["Progress", snapshot.summary.label]);
  summary.addRow(["Complete", snapshot.summary.complete]);
  summary.addRow(["Pending", snapshot.summary.pending]);
  summary.addRow(["Total", snapshot.summary.total]);
  summary.addRow([]);
  summary.addRow(["Auto-generated by ClearESG"]);
  summary.getColumn(1).width = 16;
  summary.getColumn(2).width = 48;

  const buf = await wb.xlsx.writeBuffer();
  return Buffer.from(buf);
}
