/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by Payload.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:types` to regenerate this file.
 */

/**
 * Supported timezones in IANA format.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "supportedTimezones".
 */
export type SupportedTimezones =
  | 'Pacific/Midway'
  | 'Pacific/Niue'
  | 'Pacific/Honolulu'
  | 'Pacific/Rarotonga'
  | 'America/Anchorage'
  | 'Pacific/Gambier'
  | 'America/Los_Angeles'
  | 'America/Tijuana'
  | 'America/Denver'
  | 'America/Phoenix'
  | 'America/Chicago'
  | 'America/Guatemala'
  | 'America/New_York'
  | 'America/Bogota'
  | 'America/Caracas'
  | 'America/Santiago'
  | 'America/Buenos_Aires'
  | 'America/Sao_Paulo'
  | 'Atlantic/South_Georgia'
  | 'Atlantic/Azores'
  | 'Atlantic/Cape_Verde'
  | 'Europe/London'
  | 'Europe/Berlin'
  | 'Africa/Lagos'
  | 'Europe/Athens'
  | 'Africa/Cairo'
  | 'Europe/Moscow'
  | 'Asia/Riyadh'
  | 'Asia/Dubai'
  | 'Asia/Baku'
  | 'Asia/Karachi'
  | 'Asia/Tashkent'
  | 'Asia/Calcutta'
  | 'Asia/Dhaka'
  | 'Asia/Almaty'
  | 'Asia/Jakarta'
  | 'Asia/Bangkok'
  | 'Asia/Shanghai'
  | 'Asia/Singapore'
  | 'Asia/Tokyo'
  | 'Asia/Seoul'
  | 'Australia/Brisbane'
  | 'Australia/Sydney'
  | 'Pacific/Guam'
  | 'Pacific/Noumea'
  | 'Pacific/Auckland'
  | 'Pacific/Fiji';

export interface Config {
  auth: {
    users: UserAuthOperations;
  };
  blocks: {};
  collections: {
    users: User;
    media: Media;
    organisations: Organisation;
    memberships: Membership;
    'policy-roles': PolicyRole;
    'user-policies': UserPolicy;
    'reporting-periods': ReportingPeriod;
    'metric-definitions': MetricDefinition;
    'derived-metric-definitions': DerivedMetricDefinition;
    'emission-factors': EmissionFactor;
    datapoints: Datapoint;
    evidence: Evidence;
    suppliers: Supplier;
    'scope3-sources': Scope3Source;
    'scope3-activities': Scope3Activity;
    'internal-data-requests': InternalDataRequest;
    'materiality-assessments': MaterialityAssessment;
    reports: Report;
    'audit-logs': AuditLog;
    'benchmark-stats': BenchmarkStat;
    'compliance-obligations': ComplianceObligation;
    'policy-evaluations': PolicyEvaluation;
    'framework-metrics': FrameworkMetric;
    'compliance-targets': ComplianceTarget;
    'framework-mappings': FrameworkMapping;
    'assurance-engagements': AssuranceEngagement;
    'verification-findings': VerificationFinding;
    'assurance-reports': AssuranceReport;
    'payload-kv': PayloadKv;
    'payload-locked-documents': PayloadLockedDocument;
    'payload-preferences': PayloadPreference;
    'payload-migrations': PayloadMigration;
  };
  collectionsJoins: {};
  collectionsSelect: {
    users: UsersSelect<false> | UsersSelect<true>;
    media: MediaSelect<false> | MediaSelect<true>;
    organisations: OrganisationsSelect<false> | OrganisationsSelect<true>;
    memberships: MembershipsSelect<false> | MembershipsSelect<true>;
    'policy-roles': PolicyRolesSelect<false> | PolicyRolesSelect<true>;
    'user-policies': UserPoliciesSelect<false> | UserPoliciesSelect<true>;
    'reporting-periods': ReportingPeriodsSelect<false> | ReportingPeriodsSelect<true>;
    'metric-definitions': MetricDefinitionsSelect<false> | MetricDefinitionsSelect<true>;
    'derived-metric-definitions': DerivedMetricDefinitionsSelect<false> | DerivedMetricDefinitionsSelect<true>;
    'emission-factors': EmissionFactorsSelect<false> | EmissionFactorsSelect<true>;
    datapoints: DatapointsSelect<false> | DatapointsSelect<true>;
    evidence: EvidenceSelect<false> | EvidenceSelect<true>;
    suppliers: SuppliersSelect<false> | SuppliersSelect<true>;
    'scope3-sources': Scope3SourcesSelect<false> | Scope3SourcesSelect<true>;
    'scope3-activities': Scope3ActivitiesSelect<false> | Scope3ActivitiesSelect<true>;
    'internal-data-requests': InternalDataRequestsSelect<false> | InternalDataRequestsSelect<true>;
    'materiality-assessments': MaterialityAssessmentsSelect<false> | MaterialityAssessmentsSelect<true>;
    reports: ReportsSelect<false> | ReportsSelect<true>;
    'audit-logs': AuditLogsSelect<false> | AuditLogsSelect<true>;
    'benchmark-stats': BenchmarkStatsSelect<false> | BenchmarkStatsSelect<true>;
    'compliance-obligations': ComplianceObligationsSelect<false> | ComplianceObligationsSelect<true>;
    'policy-evaluations': PolicyEvaluationsSelect<false> | PolicyEvaluationsSelect<true>;
    'framework-metrics': FrameworkMetricsSelect<false> | FrameworkMetricsSelect<true>;
    'compliance-targets': ComplianceTargetsSelect<false> | ComplianceTargetsSelect<true>;
    'framework-mappings': FrameworkMappingsSelect<false> | FrameworkMappingsSelect<true>;
    'assurance-engagements': AssuranceEngagementsSelect<false> | AssuranceEngagementsSelect<true>;
    'verification-findings': VerificationFindingsSelect<false> | VerificationFindingsSelect<true>;
    'assurance-reports': AssuranceReportsSelect<false> | AssuranceReportsSelect<true>;
    'payload-kv': PayloadKvSelect<false> | PayloadKvSelect<true>;
    'payload-locked-documents': PayloadLockedDocumentsSelect<false> | PayloadLockedDocumentsSelect<true>;
    'payload-preferences': PayloadPreferencesSelect<false> | PayloadPreferencesSelect<true>;
    'payload-migrations': PayloadMigrationsSelect<false> | PayloadMigrationsSelect<true>;
  };
  db: {
    defaultIDType: string;
  };
  fallbackLocale: null;
  globals: {};
  globalsSelect: {};
  locale: null;
  widgets: {
    collections: CollectionsWidget;
  };
  user: User;
  jobs: {
    tasks: unknown;
    workflows: unknown;
  };
}
export interface UserAuthOperations {
  forgotPassword: {
    email: string;
    password: string;
  };
  login: {
    email: string;
    password: string;
  };
  registerFirstUser: {
    email: string;
    password: string;
  };
  unlock: {
    email: string;
    password: string;
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users".
 */
export interface User {
  id: string;
  /**
   * Clerk user id — set by webhook in Phase 2
   */
  clerkId?: string | null;
  firstName?: string | null;
  lastName?: string | null;
  avatarUrl?: string | null;
  lastSeenAt?: string | null;
  updatedAt: string;
  createdAt: string;
  email: string;
  resetPasswordToken?: string | null;
  resetPasswordExpiration?: string | null;
  salt?: string | null;
  hash?: string | null;
  loginAttempts?: number | null;
  lockUntil?: string | null;
  sessions?:
    | {
        id: string;
        createdAt?: string | null;
        expiresAt: string;
      }[]
    | null;
  password?: string | null;
  collection: 'users';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media".
 */
export interface Media {
  id: string;
  alt: string;
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  focalX?: number | null;
  focalY?: number | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "organisations".
 */
export interface Organisation {
  id: string;
  name: string;
  slug: string;
  type: 'company' | 'consultancy';
  /**
   * NACE code
   */
  sector: string;
  /**
   * ISO 3166-1 alpha-2
   */
  country: string;
  employeeCount?: number | null;
  revenueBand?: ('lt_2m' | '2_10m' | '10_50m' | '50_250m' | 'gt_250m') | null;
  /**
   * MM-DD, e.g. 03-31
   */
  fiscalYearEnd?: string | null;
  /**
   * Consultancy parent — one level deep only
   */
  parentOrg?: (string | null) | Organisation;
  /**
   * Legacy white-label fields — prefer settings.branding. Kept for read fallback.
   */
  brand?: {
    logo?: (string | null) | Media;
    primaryColor?: string | null;
    domain?: string | null;
  };
  settings?: {
    branding?: {
      logo?: (string | null) | Media;
      /**
       * Dashboard primary #RRGGBB → --accent
       */
      primaryColor?: string | null;
      /**
       * Dashboard secondary #RRGGBB
       */
      secondaryColor?: string | null;
      fontFamily?: ('inter_tight' | 'plus_jakarta' | 'fraunces' | 'space_grotesk') | null;
      /**
       * Org default when the user has no personal theme cookie
       */
      defaultMode?: ('light' | 'dark') | null;
      radius?: ('sharp' | 'default' | 'soft') | null;
    };
    /**
     * Custom white-label host (consultant entitlement)
     */
    domain?: string | null;
  };
  stripeCustomerId?: string | null;
  plan?: ('free' | 'pro' | 'consultant') | null;
  subscriptionStatus?: ('none' | 'active' | 'past_due' | 'canceled') | null;
  onboardedAt?: string | null;
  /**
   * First-report guided checklist — org-scoped, not localStorage.
   */
  guideProgress?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  /**
   * Opt out of anonymised sector benchmark aggregation (ToS consent).
   */
  benchmarkOptOut?: boolean | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "memberships".
 */
export interface Membership {
  id: string;
  user: string | User;
  organisation: string | Organisation;
  role: 'owner' | 'admin' | 'contributor' | 'viewer';
  status: 'active' | 'invited' | 'revoked';
  invitedBy?: (string | null) | User;
  invitedAt?: string | null;
  acceptedAt?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "policy-roles".
 */
export interface PolicyRole {
  id: string;
  /**
   * Role name (e.g., Admin, Contributor, Viewer)
   */
  name: string;
  /**
   * Human-readable description of this role
   */
  description: string;
  defaultCapabilities: {
    /**
     * Action the role can perform
     */
    action: 'view' | 'create' | 'edit' | 'delete' | 'approve' | 'export' | 'manage-users' | 'manage-policies';
    /**
     * Resource type (e.g., datapoint, report, organisation)
     */
    resource: string;
    /**
     * Scope of access (own data, team, org-wide, or all)
     */
    scope: 'own' | 'team' | 'organisation' | 'all';
    id?: string | null;
  }[];
  /**
   * System roles (Admin, Contributor, Viewer) cannot be deleted
   */
  isSystem?: boolean | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "user-policies".
 */
export interface UserPolicy {
  id: string;
  /**
   * User this policy assignment applies to
   */
  user: string | User;
  /**
   * Organisation context for this policy (user may have different roles per org)
   */
  organisation: string | Organisation;
  /**
   * Assigned role (determines default capabilities)
   */
  role: string | PolicyRole;
  /**
   * Custom capability overrides. Admin can add/remove capabilities beyond the role
   */
  customCapabilities?:
    | {
        action: 'view' | 'create' | 'edit' | 'delete' | 'approve' | 'export' | 'manage-users' | 'manage-policies';
        /**
         * Resource type (e.g., datapoint, report)
         */
        resource: string;
        scope: 'own' | 'team' | 'organisation' | 'all';
        /**
         * TRUE = grant this capability, FALSE = deny/revoke
         */
        isGrant?: boolean | null;
        id?: string | null;
      }[]
    | null;
  /**
   * Admin notes about why this custom policy was set
   */
  notes?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "reporting-periods".
 */
export interface ReportingPeriod {
  id: string;
  organisation: string | Organisation;
  label: string;
  startDate: string;
  endDate: string;
  status: 'open' | 'locked' | 'published';
  lockedAt?: string | null;
  lockedBy?: (string | null) | User;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "metric-definitions".
 */
export interface MetricDefinition {
  id: string;
  key: string;
  label: string;
  description: string;
  unit?: string | null;
  category: 'E' | 'S' | 'G';
  inputType: 'number' | 'boolean' | 'select';
  helpText: string;
  exampleSource: string;
  /**
   * Which §5 formula term this feeds
   */
  calcRole: string;
  frameworkMappings?:
    | {
        framework: 'CSRD_SET1' | 'CSRD_SIMPLIFIED' | 'BRSR' | 'VSME' | 'GRI' | 'ISSB_S1' | 'ISSB_S2' | 'EU_TAXONOMY';
        /**
         * Disclosure code (product alias: disclosureCode). Not a datapoint document id.
         */
        datapointRef: string;
        /**
         * Human disclosure name (counsel placeholder OK).
         */
        label?: string | null;
        required?: boolean | null;
        /**
         * When true, data contributes to this disclosure — never alone satisfies it.
         */
        contributionOnly?: boolean | null;
        validFrom?: string | null;
        validUntil?: string | null;
        sourceDoc?: string | null;
        sourceSheet?: string | null;
        sourceRow?: number | null;
        extractedAt?: string | null;
        id?: string | null;
      }[]
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "derived-metric-definitions".
 */
export interface DerivedMetricDefinition {
  id: string;
  key: string;
  label: string;
  description: string;
  unit: string;
  frameworkMappings?:
    | {
        framework: 'CSRD_SET1' | 'CSRD_SIMPLIFIED' | 'BRSR' | 'VSME' | 'GRI' | 'ISSB_S1' | 'ISSB_S2' | 'EU_TAXONOMY';
        /**
         * Disclosure code (product alias: disclosureCode). Not a datapoint document id.
         */
        datapointRef: string;
        /**
         * Human disclosure name (counsel placeholder OK).
         */
        label?: string | null;
        required?: boolean | null;
        /**
         * When true, data contributes to this disclosure — never alone satisfies it.
         */
        contributionOnly?: boolean | null;
        validFrom?: string | null;
        validUntil?: string | null;
        sourceDoc: string;
        sourceSheet: string;
        sourceRow: number;
        extractedAt: string;
        /**
         * Must be true to surface in product mappings
         */
        approved: boolean;
        id?: string | null;
      }[]
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "emission-factors".
 */
export interface EmissionFactor {
  id: string;
  key: string;
  label: string;
  value: number;
  /**
   * e.g. kgCO2e/kWh
   */
  unit: string;
  scope: '1' | '2' | '3';
  source: 'DEFRA' | 'EPA' | 'IEA' | 'CEA_India' | 'GHGProtocol' | 'EEA' | 'NationalInventory';
  sourceUrl: string;
  publicationYear: number;
  /**
   * ISO 3166-1 alpha-2 or GLOBAL
   */
  region: string;
  validFrom: string;
  validUntil?: string | null;
  supersededBy?: (string | null) | EmissionFactor;
  /**
   * e.g. OGL v3.0, US public domain, Government of India
   */
  licence: string;
  /**
   * Visible attribution string required by the licence (OGL etc.)
   */
  attributionText: string;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "datapoints".
 */
export interface Datapoint {
  id: string;
  organisation: string | Organisation;
  period: string | ReportingPeriod;
  metricKey: string;
  value?: number | null;
  unit?: string | null;
  quality: 'measured' | 'calculated' | 'estimated' | 'missing';
  /**
   * Where this Scope 3 figure came from. Independent of quality (measured vs estimated).
   */
  provenance?: ('supplier_primary' | 'spend_estimate' | 'manual') | null;
  /**
   * Supplier that produced this contribution, when applicable
   */
  supplier?: (string | null) | Supplier;
  /**
   * Sentinel unique-index key. Empty string = no supplier. Never null.
   */
  supplierKey?: string | null;
  /**
   * Pinned EmissionFactor id used when this value was derived
   */
  factorId?: string | null;
  evidence?: (string | Evidence)[] | null;
  source: 'manual' | 'import' | 'supplier' | 'estimate' | 'api' | 'internal_survey';
  approvalState: 'pending' | 'approved' | 'rejected';
  /**
   * Required when approvalState is rejected.
   */
  approvalReason?: string | null;
  assignedTo?: (string | null) | User;
  dueDate?: string | null;
  taskStatus?: ('open' | 'submitted' | 'approved') | null;
  enteredBy?: (string | null) | User;
  enteredAt?: string | null;
  note?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "suppliers".
 */
export interface Supplier {
  id: string;
  organisation: string | Organisation;
  name: string;
  contactEmail: string;
  category: 'purchased_goods' | 'capital_goods' | 'transport' | 'waste' | 'business_travel' | 'other';
  annualSpend?: number | null;
  /**
   * Reporting period this request token is bound to
   */
  requestPeriod?: (string | null) | ReportingPeriod;
  requestToken?: string | null;
  requestStatus?: ('not_sent' | 'sent' | 'opened' | 'submitted' | 'declined') | null;
  sentAt?: string | null;
  requestExpiresAt?: string | null;
  respondedAt?: string | null;
  lastReminderAt?: string | null;
  submittedData?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  reminderCount?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "evidence".
 */
export interface Evidence {
  id: string;
  organisation: string | Organisation;
  file: string | Media;
  filename: string;
  mimeType?: string | null;
  size?: number | null;
  sha256: string;
  uploadedBy?: (string | null) | User;
  uploadedAt: string;
  /**
   * Start of the period this evidence covers (for assurance freshness).
   */
  coverageStart?: string | null;
  /**
   * End of the period this evidence covers (for assurance freshness).
   */
  coverageEnd?: string | null;
  linkedDatapoints?: (string | Datapoint)[] | null;
  /**
   * Why this document proves the figure — shown to auditors and reviewers.
   */
  whyNote?: string | null;
  extractedData?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  /**
   * OCR is not productized; new uploads should set skipped until a worker ships.
   */
  ocrStatus?: ('pending' | 'done' | 'failed' | 'skipped') | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "scope3-sources".
 */
export interface Scope3Source {
  id: string;
  organisation: string | Organisation;
  type: 'supplier' | 'investment' | 'waste' | 'business_travel' | 'employee_commute';
  name: string;
  description?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  /**
   * Emissions factor: value (number), unit (string), source (DEFRA/IPCC/CDP/Custom), year (number), confidence (high/medium/low)
   */
  emissionsFactor:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  /**
   * Array of activity fields: name (string), unit (string), description (string), required (boolean)
   */
  activityDataFields:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "scope3-activities".
 */
export interface Scope3Activity {
  id: string;
  organisation: string | Organisation;
  source: string | Scope3Source;
  period: string | ReportingPeriod;
  /**
   * JSON object with activity field values
   */
  activityData:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  /**
   * Calculated tonnes CO2e (readonly, auto-calculated)
   */
  calculatedEmissions: number;
  status: 'draft' | 'validated' | 'approved';
  /**
   * Supporting documents for audit trail
   */
  evidence?: (string | Evidence)[] | null;
  /**
   * User who created this activity
   */
  enteredBy?: (string | null) | User;
  /**
   * User who approved this activity
   */
  approvedBy?: (string | null) | User;
  approvedAt?: string | null;
  /**
   * Notes from validation process
   */
  validationNotes?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "internal-data-requests".
 */
export interface InternalDataRequest {
  id: string;
  organisation: string | Organisation;
  period: string | ReportingPeriod;
  title: string;
  assignee: string | User;
  metricKeys: {
    key: string;
    id?: string | null;
  }[];
  requestStatus?: ('not_sent' | 'sent' | 'opened' | 'submitted') | null;
  dueDate?: string | null;
  sentAt?: string | null;
  openedAt?: string | null;
  submittedAt?: string | null;
  lastReminderAt?: string | null;
  reminderCount?: number | null;
  createdBy?: (string | null) | User;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "materiality-assessments".
 */
export interface MaterialityAssessment {
  id: string;
  organisation: string | Organisation;
  period: string | ReportingPeriod;
  status: 'draft' | 'final';
  topics?:
    | {
        esrsTopic: string;
        impactSeverity?: number | null;
        impactScope?: number | null;
        impactIrremediability?: number | null;
        financialMagnitude?: number | null;
        financialLikelihood?: number | null;
        impactScore: number;
        financialScore: number;
        rationale?: string | null;
        /**
         * Auditor trail — sector starting position accepted vs actively changed.
         */
        origin?: ('suggested' | 'adjusted') | null;
        decidedBy?: (string | null) | User;
        decidedAt?: string | null;
        id?: string | null;
      }[]
    | null;
  matrixSnapshot?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  narrative?: string | null;
  finalisedAt?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "reports".
 */
export interface Report {
  id: string;
  organisation: string | Organisation;
  period: string | ReportingPeriod;
  framework: 'CSRD_SET1' | 'CSRD_SIMPLIFIED' | 'BRSR' | 'VSME' | 'GRI' | 'CUSTOM';
  version: number;
  status: 'draft' | 'published';
  scores?: {
    overall?: number | null;
    e?: number | null;
    s?: number | null;
    g?: number | null;
  };
  emissions?: {
    scope1?: number | null;
    scope2?: number | null;
    scope3?: number | null;
  };
  dataQualityPct?: number | null;
  factorVersionsUsed?: (string | EmissionFactor)[] | null;
  /**
   * Immutable publish payload — never mutate after published
   */
  snapshot?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  pdfUrl?: string | null;
  shareToken?: string | null;
  /**
   * Token for read-only /a/[token] Assurance Room (no Membership role).
   */
  assuranceToken?: string | null;
  shareExpiresAt?: string | null;
  viewCount?: number | null;
  publishedAt?: string | null;
  publishedBy?: (string | null) | User;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "audit-logs".
 */
export interface AuditLog {
  id: string;
  organisation: string | Organisation;
  /**
   * Optional — public supplier token submits may omit actor; reconstruct from after.tokenId / supplierId
   */
  actor?: (string | null) | User;
  action: string;
  entityType: string;
  entityId: string;
  before?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  after?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  ip?: string | null;
  userAgent?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "benchmark-stats".
 */
export interface BenchmarkStat {
  id: string;
  sector: string;
  sizeBand: string;
  metricKey: string;
  period: string;
  p25: number;
  p50: number;
  p75: number;
  cohortSize: number;
  /**
   * As-of timestamp for this cohort row.
   */
  computedAt?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "compliance-obligations".
 */
export interface ComplianceObligation {
  id: string;
  organisation: string | Organisation;
  wave: '1' | '2' | '3' | 'brsr_listed' | 'brsr_supply' | 'other';
  /**
   * ISO country or region code, e.g. EU, IN, GB
   */
  jurisdiction: string;
  standardVersion: 'CSRD_SET1' | 'CSRD_SIMPLIFIED' | 'BRSR' | 'VSME' | 'GRI';
  /**
   * e.g. "FY2025" or "2025-26"
   */
  firstReportingFY: string;
  /**
   * Countdown the Compliance Runway displays. Leave empty for voluntary / not in mandatory scope — never invent a date.
   */
  filingDeadline?: string | null;
  notes?: string | null;
  /**
   * Plain-language why this obligation was derived or overridden
   */
  derivationReason?: string | null;
  /**
   * needs_confirmation surfaces a gentle Runway prompt; derived is still confirmable, never legal advice
   */
  confidence?: ('derived' | 'needs_confirmation') | null;
  /**
   * Manual overrides are sticky on baseline change — do not silently overwrite
   */
  source?: ('engine' | 'manual') | null;
  /**
   * When an Owner/Admin confirmed or overrode the obligation
   */
  confirmedAt?: string | null;
  /**
   * Baseline snapshot used at last engine derivation
   */
  derivedInputs?: {
    country?: string | null;
    headcount?: number | null;
    revenueBand?: ('lt_2m' | '2_10m' | '10_50m' | '50_250m' | 'gt_250m') | null;
    asOf?: string | null;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "policy-evaluations".
 */
export interface PolicyEvaluation {
  id: string;
  /**
   * User ID who attempted the action
   */
  userId: string;
  /**
   * Organisation context
   */
  organisationId: string;
  /**
   * Action attempted (view, create, edit, delete, etc)
   */
  action: string;
  /**
   * Resource type (datapoint, report, organisation, etc)
   */
  resource: string;
  /**
   * ID of the specific resource
   */
  resourceId: string;
  /**
   * Whether the action was allowed or denied
   */
  decision: 'allowed' | 'denied';
  /**
   * Brief explanation of decision (e.g., 'role does not have permission')
   */
  reason?: string | null;
  /**
   * User's role at time of evaluation
   */
  userRole?: string | null;
  /**
   * When this action was evaluated
   */
  evaluatedAt: string;
  /**
   * IP address of the request
   */
  ip?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "framework-metrics".
 */
export interface FrameworkMetric {
  id: string;
  framework: 'csrd' | 'brsr' | 'gri' | 'sasb';
  /**
   * Unique identifier, e.g., csrd_scope1_intensity, brsr_total_emissions
   */
  metricKey: string;
  /**
   * Human-readable metric name
   */
  label: string;
  /**
   * Unit of measurement, e.g., tCO2e, tCO2e/€M revenue, kg CO2e/unit
   */
  unit: string;
  /**
   * Detailed metric definition and calculation methodology
   */
  description?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  /**
   * Type of data this metric represents
   */
  dataType: 'emissions' | 'intensity' | 'percentage' | 'custom';
  /**
   * Whether this metric is required for framework compliance
   */
  required: boolean;
  /**
   * Calculation details: formula (string), dependencies (string[]), parameters (object)
   */
  calculationMethod?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "compliance-targets".
 */
export interface ComplianceTarget {
  id: string;
  organisation: string | Organisation;
  framework: 'csrd' | 'brsr' | 'gri' | 'sasb';
  /**
   * Reference to FrameworkMetrics.metricKey
   */
  metricKey: string;
  /**
   * Cached metric label for readability
   */
  metricLabel?: string | null;
  /**
   * Target value for this metric
   */
  targetValue: number;
  /**
   * Year from which emissions are measured
   */
  baselineYear: number;
  /**
   * Year by which target should be achieved
   */
  targetYear: number;
  /**
   * Current status relative to trajectory
   */
  status: 'on-track' | 'at-risk' | 'off-track';
  /**
   * Internal notes about this target
   */
  notes?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  /**
   * Approval workflow status
   */
  approvalStatus?: ('draft' | 'submitted' | 'approved' | 'rejected') | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "framework-mappings".
 */
export interface FrameworkMapping {
  id: string;
  organisation: string | Organisation;
  /**
   * Reporting period for this mapping
   */
  period: string | ReportingPeriod;
  framework: 'csrd' | 'brsr' | 'gri' | 'sasb';
  /**
   * Emissions snapshot: scope1 (number), scope2 (number), scope3 (number), total (number)
   */
  emissionsData:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  /**
   * Additional context: revenue (number), employees (number), units (number), currency (string), etc.
   */
  metadata?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  /**
   * Array of calculated metrics: metricKey (string), value (number), unit (string), confidence (high/medium/low), calculatedAt (ISO string)
   */
  metrics:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  /**
   * Compliance status summary (compliant, partial, non-compliant)
   */
  complianceStatus?: string | null;
  /**
   * Array of identified gaps: metricKey (string), label (string), impact (high/medium/low), estimatedImpactOnScore (number)
   */
  dataGaps?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  /**
   * Array of detected anomalies: metricKey (string), value (number), expected (number), deviation (number), severity (low/medium/high)
   */
  anomalies?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  /**
   * Overall confidence in this mapping (0-100)
   */
  confidenceLevel?: number | null;
  /**
   * When this mapping was calculated
   */
  calculatedAt: string;
  /**
   * User who triggered the calculation
   */
  calculatedBy?: (string | null) | User;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "assurance-engagements".
 */
export interface AssuranceEngagement {
  id: string;
  organisation: string | Organisation;
  reportingPeriod: string | ReportingPeriod;
  provider: {
    /**
     * Assurance provider name
     */
    name: string;
    /**
     * Primary contact email
     */
    email: string;
    /**
     * Primary contact name
     */
    contactPerson?: string | null;
    /**
     * Provider organization name
     */
    providerOrg?: string | null;
  };
  scope: 'scope1' | 'scope2' | 'scope3' | 'all';
  /**
   * Optional framework focus
   */
  framework?: ('csrd' | 'brsr' | 'gri' | 'sasb') | null;
  status: 'draft' | 'submitted' | 'reviewing' | 'findings_submitted' | 'approved' | 'signed_off';
  /**
   * When engagement was requested
   */
  requestedAt: string;
  /**
   * When engagement was formally submitted to provider
   */
  submittedAt?: string | null;
  /**
   * When findings were approved by organization
   */
  approvedAt?: string | null;
  /**
   * When provider signed off on assurance
   */
  signedOffAt?: string | null;
  /**
   * Data gaps identified for this engagement
   */
  dataGaps?:
    | {
        /**
         * Missing metric or data point
         */
        metric: string;
        severity: 'high' | 'medium' | 'low';
        /**
         * Why this metric is missing or incomplete
         */
        description: string;
        id?: string | null;
      }[]
    | null;
  /**
   * Internal notes about engagement
   */
  notes?: string | null;
  /**
   * User who created engagement
   */
  createdBy?: (string | null) | User;
  /**
   * Provider user assigned to this engagement (external user)
   */
  assignedTo?: (string | null) | User;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "verification-findings".
 */
export interface VerificationFinding {
  id: string;
  /**
   * Associated assurance engagement
   */
  engagement: string | AssuranceEngagement;
  /**
   * Type of finding
   */
  category: 'data-quality' | 'methodology' | 'scope' | 'calculation' | 'completeness' | 'other';
  severity: 'critical' | 'major' | 'minor' | 'info';
  /**
   * Brief finding title
   */
  title: string;
  /**
   * Detailed description of finding
   */
  description: string;
  /**
   * Which metric/datapoint this affects
   */
  affectedMetric?: string | null;
  /**
   * Supporting evidence links/references
   */
  evidence?:
    | {
        /**
         * URL or reference to evidence
         */
        url?: string | null;
        /**
         * How this supports the finding
         */
        description?: string | null;
        id?: string | null;
      }[]
    | null;
  /**
   * Business impact of this finding
   */
  impact?: ('high' | 'medium' | 'low') | null;
  /**
   * Recommended action/resolution
   */
  recommendation?: string | null;
  status: 'open' | 'acknowledged' | 'resolved' | 'closed';
  /**
   * Provider user who submitted this finding
   */
  submittedBy: string | User;
  /**
   * When finding was submitted
   */
  submittedAt: string;
  /**
   * When finding was resolved
   */
  resolvedAt?: string | null;
  /**
   * Notes on how finding was resolved
   */
  resolutionNotes?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "assurance-reports".
 */
export interface AssuranceReport {
  id: string;
  /**
   * Associated assurance engagement
   */
  engagement: string | AssuranceEngagement;
  organisation: string | Organisation;
  reportingPeriod: string | ReportingPeriod;
  status: 'draft' | 'approved' | 'published';
  /**
   * Audit standard assurance level (limited vs reasonable)
   */
  assuranceLevel: 'limited' | 'reasonable';
  /**
   * Formal assurance statement text to be published
   */
  assuranceStatement: string;
  /**
   * High-level summary for stakeholders
   */
  executiveSummary?: string | null;
  /**
   * Count of findings by severity
   */
  findingsSummary: {
    total: number;
    critical: number;
    major: number;
    minor: number;
    info: number;
  };
  /**
   * Provider sign-off information
   */
  provider: {
    /**
     * Provider organization name
     */
    name: string;
    /**
     * Provider credentials/certifications
     */
    credentials?: string | null;
    /**
     * Date of provider signature
     */
    signatureDate: string;
    /**
     * Name of signatory from provider
     */
    signatureName: string;
  };
  /**
   * When report was initially generated
   */
  generatedAt: string;
  /**
   * When report was published
   */
  publishedAt?: string | null;
  /**
   * User who published the report
   */
  publishedBy?: (string | null) | User;
  /**
   * Summary of data gaps identified and addressed
   */
  dataGapsSummary?:
    | {
        metric: string;
        severity: 'high' | 'medium' | 'low';
        /**
         * How data gap was addressed
         */
        resolution?: string | null;
        id?: string | null;
      }[]
    | null;
  /**
   * Overall assurance confidence score (0-100)
   */
  assuranceScore?: number | null;
  /**
   * Generated PDF report (if exported)
   */
  pdf?: (string | null) | Media;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv".
 */
export interface PayloadKv {
  id: string;
  key: string;
  data:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents".
 */
export interface PayloadLockedDocument {
  id: string;
  document?:
    | ({
        relationTo: 'users';
        value: string | User;
      } | null)
    | ({
        relationTo: 'media';
        value: string | Media;
      } | null)
    | ({
        relationTo: 'organisations';
        value: string | Organisation;
      } | null)
    | ({
        relationTo: 'memberships';
        value: string | Membership;
      } | null)
    | ({
        relationTo: 'policy-roles';
        value: string | PolicyRole;
      } | null)
    | ({
        relationTo: 'user-policies';
        value: string | UserPolicy;
      } | null)
    | ({
        relationTo: 'reporting-periods';
        value: string | ReportingPeriod;
      } | null)
    | ({
        relationTo: 'metric-definitions';
        value: string | MetricDefinition;
      } | null)
    | ({
        relationTo: 'derived-metric-definitions';
        value: string | DerivedMetricDefinition;
      } | null)
    | ({
        relationTo: 'emission-factors';
        value: string | EmissionFactor;
      } | null)
    | ({
        relationTo: 'datapoints';
        value: string | Datapoint;
      } | null)
    | ({
        relationTo: 'evidence';
        value: string | Evidence;
      } | null)
    | ({
        relationTo: 'suppliers';
        value: string | Supplier;
      } | null)
    | ({
        relationTo: 'scope3-sources';
        value: string | Scope3Source;
      } | null)
    | ({
        relationTo: 'scope3-activities';
        value: string | Scope3Activity;
      } | null)
    | ({
        relationTo: 'internal-data-requests';
        value: string | InternalDataRequest;
      } | null)
    | ({
        relationTo: 'materiality-assessments';
        value: string | MaterialityAssessment;
      } | null)
    | ({
        relationTo: 'reports';
        value: string | Report;
      } | null)
    | ({
        relationTo: 'audit-logs';
        value: string | AuditLog;
      } | null)
    | ({
        relationTo: 'benchmark-stats';
        value: string | BenchmarkStat;
      } | null)
    | ({
        relationTo: 'compliance-obligations';
        value: string | ComplianceObligation;
      } | null)
    | ({
        relationTo: 'policy-evaluations';
        value: string | PolicyEvaluation;
      } | null)
    | ({
        relationTo: 'framework-metrics';
        value: string | FrameworkMetric;
      } | null)
    | ({
        relationTo: 'compliance-targets';
        value: string | ComplianceTarget;
      } | null)
    | ({
        relationTo: 'framework-mappings';
        value: string | FrameworkMapping;
      } | null)
    | ({
        relationTo: 'assurance-engagements';
        value: string | AssuranceEngagement;
      } | null)
    | ({
        relationTo: 'verification-findings';
        value: string | VerificationFinding;
      } | null)
    | ({
        relationTo: 'assurance-reports';
        value: string | AssuranceReport;
      } | null);
  globalSlug?: string | null;
  user: {
    relationTo: 'users';
    value: string | User;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences".
 */
export interface PayloadPreference {
  id: string;
  user: {
    relationTo: 'users';
    value: string | User;
  };
  key?: string | null;
  value?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations".
 */
export interface PayloadMigration {
  id: string;
  name?: string | null;
  batch?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users_select".
 */
export interface UsersSelect<T extends boolean = true> {
  clerkId?: T;
  firstName?: T;
  lastName?: T;
  avatarUrl?: T;
  lastSeenAt?: T;
  updatedAt?: T;
  createdAt?: T;
  email?: T;
  resetPasswordToken?: T;
  resetPasswordExpiration?: T;
  salt?: T;
  hash?: T;
  loginAttempts?: T;
  lockUntil?: T;
  sessions?:
    | T
    | {
        id?: T;
        createdAt?: T;
        expiresAt?: T;
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media_select".
 */
export interface MediaSelect<T extends boolean = true> {
  alt?: T;
  updatedAt?: T;
  createdAt?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
  focalX?: T;
  focalY?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "organisations_select".
 */
export interface OrganisationsSelect<T extends boolean = true> {
  name?: T;
  slug?: T;
  type?: T;
  sector?: T;
  country?: T;
  employeeCount?: T;
  revenueBand?: T;
  fiscalYearEnd?: T;
  parentOrg?: T;
  brand?:
    | T
    | {
        logo?: T;
        primaryColor?: T;
        domain?: T;
      };
  settings?:
    | T
    | {
        branding?:
          | T
          | {
              logo?: T;
              primaryColor?: T;
              secondaryColor?: T;
              fontFamily?: T;
              defaultMode?: T;
              radius?: T;
            };
        domain?: T;
      };
  stripeCustomerId?: T;
  plan?: T;
  subscriptionStatus?: T;
  onboardedAt?: T;
  guideProgress?: T;
  benchmarkOptOut?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "memberships_select".
 */
export interface MembershipsSelect<T extends boolean = true> {
  user?: T;
  organisation?: T;
  role?: T;
  status?: T;
  invitedBy?: T;
  invitedAt?: T;
  acceptedAt?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "policy-roles_select".
 */
export interface PolicyRolesSelect<T extends boolean = true> {
  name?: T;
  description?: T;
  defaultCapabilities?:
    | T
    | {
        action?: T;
        resource?: T;
        scope?: T;
        id?: T;
      };
  isSystem?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "user-policies_select".
 */
export interface UserPoliciesSelect<T extends boolean = true> {
  user?: T;
  organisation?: T;
  role?: T;
  customCapabilities?:
    | T
    | {
        action?: T;
        resource?: T;
        scope?: T;
        isGrant?: T;
        id?: T;
      };
  notes?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "reporting-periods_select".
 */
export interface ReportingPeriodsSelect<T extends boolean = true> {
  organisation?: T;
  label?: T;
  startDate?: T;
  endDate?: T;
  status?: T;
  lockedAt?: T;
  lockedBy?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "metric-definitions_select".
 */
export interface MetricDefinitionsSelect<T extends boolean = true> {
  key?: T;
  label?: T;
  description?: T;
  unit?: T;
  category?: T;
  inputType?: T;
  helpText?: T;
  exampleSource?: T;
  calcRole?: T;
  frameworkMappings?:
    | T
    | {
        framework?: T;
        datapointRef?: T;
        label?: T;
        required?: T;
        contributionOnly?: T;
        validFrom?: T;
        validUntil?: T;
        sourceDoc?: T;
        sourceSheet?: T;
        sourceRow?: T;
        extractedAt?: T;
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "derived-metric-definitions_select".
 */
export interface DerivedMetricDefinitionsSelect<T extends boolean = true> {
  key?: T;
  label?: T;
  description?: T;
  unit?: T;
  frameworkMappings?:
    | T
    | {
        framework?: T;
        datapointRef?: T;
        label?: T;
        required?: T;
        contributionOnly?: T;
        validFrom?: T;
        validUntil?: T;
        sourceDoc?: T;
        sourceSheet?: T;
        sourceRow?: T;
        extractedAt?: T;
        approved?: T;
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "emission-factors_select".
 */
export interface EmissionFactorsSelect<T extends boolean = true> {
  key?: T;
  label?: T;
  value?: T;
  unit?: T;
  scope?: T;
  source?: T;
  sourceUrl?: T;
  publicationYear?: T;
  region?: T;
  validFrom?: T;
  validUntil?: T;
  supersededBy?: T;
  licence?: T;
  attributionText?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "datapoints_select".
 */
export interface DatapointsSelect<T extends boolean = true> {
  organisation?: T;
  period?: T;
  metricKey?: T;
  value?: T;
  unit?: T;
  quality?: T;
  provenance?: T;
  supplier?: T;
  supplierKey?: T;
  factorId?: T;
  evidence?: T;
  source?: T;
  approvalState?: T;
  approvalReason?: T;
  assignedTo?: T;
  dueDate?: T;
  taskStatus?: T;
  enteredBy?: T;
  enteredAt?: T;
  note?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "evidence_select".
 */
export interface EvidenceSelect<T extends boolean = true> {
  organisation?: T;
  file?: T;
  filename?: T;
  mimeType?: T;
  size?: T;
  sha256?: T;
  uploadedBy?: T;
  uploadedAt?: T;
  coverageStart?: T;
  coverageEnd?: T;
  linkedDatapoints?: T;
  whyNote?: T;
  extractedData?: T;
  ocrStatus?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "suppliers_select".
 */
export interface SuppliersSelect<T extends boolean = true> {
  organisation?: T;
  name?: T;
  contactEmail?: T;
  category?: T;
  annualSpend?: T;
  requestPeriod?: T;
  requestToken?: T;
  requestStatus?: T;
  sentAt?: T;
  requestExpiresAt?: T;
  respondedAt?: T;
  lastReminderAt?: T;
  submittedData?: T;
  reminderCount?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "scope3-sources_select".
 */
export interface Scope3SourcesSelect<T extends boolean = true> {
  organisation?: T;
  type?: T;
  name?: T;
  description?: T;
  emissionsFactor?: T;
  activityDataFields?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "scope3-activities_select".
 */
export interface Scope3ActivitiesSelect<T extends boolean = true> {
  organisation?: T;
  source?: T;
  period?: T;
  activityData?: T;
  calculatedEmissions?: T;
  status?: T;
  evidence?: T;
  enteredBy?: T;
  approvedBy?: T;
  approvedAt?: T;
  validationNotes?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "internal-data-requests_select".
 */
export interface InternalDataRequestsSelect<T extends boolean = true> {
  organisation?: T;
  period?: T;
  title?: T;
  assignee?: T;
  metricKeys?:
    | T
    | {
        key?: T;
        id?: T;
      };
  requestStatus?: T;
  dueDate?: T;
  sentAt?: T;
  openedAt?: T;
  submittedAt?: T;
  lastReminderAt?: T;
  reminderCount?: T;
  createdBy?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "materiality-assessments_select".
 */
export interface MaterialityAssessmentsSelect<T extends boolean = true> {
  organisation?: T;
  period?: T;
  status?: T;
  topics?:
    | T
    | {
        esrsTopic?: T;
        impactSeverity?: T;
        impactScope?: T;
        impactIrremediability?: T;
        financialMagnitude?: T;
        financialLikelihood?: T;
        impactScore?: T;
        financialScore?: T;
        rationale?: T;
        origin?: T;
        decidedBy?: T;
        decidedAt?: T;
        id?: T;
      };
  matrixSnapshot?: T;
  narrative?: T;
  finalisedAt?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "reports_select".
 */
export interface ReportsSelect<T extends boolean = true> {
  organisation?: T;
  period?: T;
  framework?: T;
  version?: T;
  status?: T;
  scores?:
    | T
    | {
        overall?: T;
        e?: T;
        s?: T;
        g?: T;
      };
  emissions?:
    | T
    | {
        scope1?: T;
        scope2?: T;
        scope3?: T;
      };
  dataQualityPct?: T;
  factorVersionsUsed?: T;
  snapshot?: T;
  pdfUrl?: T;
  shareToken?: T;
  assuranceToken?: T;
  shareExpiresAt?: T;
  viewCount?: T;
  publishedAt?: T;
  publishedBy?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "audit-logs_select".
 */
export interface AuditLogsSelect<T extends boolean = true> {
  organisation?: T;
  actor?: T;
  action?: T;
  entityType?: T;
  entityId?: T;
  before?: T;
  after?: T;
  ip?: T;
  userAgent?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "benchmark-stats_select".
 */
export interface BenchmarkStatsSelect<T extends boolean = true> {
  sector?: T;
  sizeBand?: T;
  metricKey?: T;
  period?: T;
  p25?: T;
  p50?: T;
  p75?: T;
  cohortSize?: T;
  computedAt?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "compliance-obligations_select".
 */
export interface ComplianceObligationsSelect<T extends boolean = true> {
  organisation?: T;
  wave?: T;
  jurisdiction?: T;
  standardVersion?: T;
  firstReportingFY?: T;
  filingDeadline?: T;
  notes?: T;
  derivationReason?: T;
  confidence?: T;
  source?: T;
  confirmedAt?: T;
  derivedInputs?:
    | T
    | {
        country?: T;
        headcount?: T;
        revenueBand?: T;
        asOf?: T;
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "policy-evaluations_select".
 */
export interface PolicyEvaluationsSelect<T extends boolean = true> {
  userId?: T;
  organisationId?: T;
  action?: T;
  resource?: T;
  resourceId?: T;
  decision?: T;
  reason?: T;
  userRole?: T;
  evaluatedAt?: T;
  ip?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "framework-metrics_select".
 */
export interface FrameworkMetricsSelect<T extends boolean = true> {
  framework?: T;
  metricKey?: T;
  label?: T;
  unit?: T;
  description?: T;
  dataType?: T;
  required?: T;
  calculationMethod?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "compliance-targets_select".
 */
export interface ComplianceTargetsSelect<T extends boolean = true> {
  organisation?: T;
  framework?: T;
  metricKey?: T;
  metricLabel?: T;
  targetValue?: T;
  baselineYear?: T;
  targetYear?: T;
  status?: T;
  notes?: T;
  approvalStatus?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "framework-mappings_select".
 */
export interface FrameworkMappingsSelect<T extends boolean = true> {
  organisation?: T;
  period?: T;
  framework?: T;
  emissionsData?: T;
  metadata?: T;
  metrics?: T;
  complianceStatus?: T;
  dataGaps?: T;
  anomalies?: T;
  confidenceLevel?: T;
  calculatedAt?: T;
  calculatedBy?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "assurance-engagements_select".
 */
export interface AssuranceEngagementsSelect<T extends boolean = true> {
  organisation?: T;
  reportingPeriod?: T;
  provider?:
    | T
    | {
        name?: T;
        email?: T;
        contactPerson?: T;
        providerOrg?: T;
      };
  scope?: T;
  framework?: T;
  status?: T;
  requestedAt?: T;
  submittedAt?: T;
  approvedAt?: T;
  signedOffAt?: T;
  dataGaps?:
    | T
    | {
        metric?: T;
        severity?: T;
        description?: T;
        id?: T;
      };
  notes?: T;
  createdBy?: T;
  assignedTo?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "verification-findings_select".
 */
export interface VerificationFindingsSelect<T extends boolean = true> {
  engagement?: T;
  category?: T;
  severity?: T;
  title?: T;
  description?: T;
  affectedMetric?: T;
  evidence?:
    | T
    | {
        url?: T;
        description?: T;
        id?: T;
      };
  impact?: T;
  recommendation?: T;
  status?: T;
  submittedBy?: T;
  submittedAt?: T;
  resolvedAt?: T;
  resolutionNotes?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "assurance-reports_select".
 */
export interface AssuranceReportsSelect<T extends boolean = true> {
  engagement?: T;
  organisation?: T;
  reportingPeriod?: T;
  status?: T;
  assuranceLevel?: T;
  assuranceStatement?: T;
  executiveSummary?: T;
  findingsSummary?:
    | T
    | {
        total?: T;
        critical?: T;
        major?: T;
        minor?: T;
        info?: T;
      };
  provider?:
    | T
    | {
        name?: T;
        credentials?: T;
        signatureDate?: T;
        signatureName?: T;
      };
  generatedAt?: T;
  publishedAt?: T;
  publishedBy?: T;
  dataGapsSummary?:
    | T
    | {
        metric?: T;
        severity?: T;
        resolution?: T;
        id?: T;
      };
  assuranceScore?: T;
  pdf?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv_select".
 */
export interface PayloadKvSelect<T extends boolean = true> {
  key?: T;
  data?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents_select".
 */
export interface PayloadLockedDocumentsSelect<T extends boolean = true> {
  document?: T;
  globalSlug?: T;
  user?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences_select".
 */
export interface PayloadPreferencesSelect<T extends boolean = true> {
  user?: T;
  key?: T;
  value?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations_select".
 */
export interface PayloadMigrationsSelect<T extends boolean = true> {
  name?: T;
  batch?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "collections_widget".
 */
export interface CollectionsWidget {
  data?: {
    [k: string]: unknown;
  };
  width: 'full';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "auth".
 */
export interface Auth {
  [k: string]: unknown;
}


declare module 'payload' {
  export interface GeneratedTypes extends Config {}
}