/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by Payload.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:types` to regenerate this file.
 */

/**
 * Supported timezones in IANA format.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "supportedTimezones".
 */
export type SupportedTimezones =
  | 'Pacific/Midway'
  | 'Pacific/Niue'
  | 'Pacific/Honolulu'
  | 'Pacific/Rarotonga'
  | 'America/Anchorage'
  | 'Pacific/Gambier'
  | 'America/Los_Angeles'
  | 'America/Tijuana'
  | 'America/Denver'
  | 'America/Phoenix'
  | 'America/Chicago'
  | 'America/Guatemala'
  | 'America/New_York'
  | 'America/Bogota'
  | 'America/Caracas'
  | 'America/Santiago'
  | 'America/Buenos_Aires'
  | 'America/Sao_Paulo'
  | 'Atlantic/South_Georgia'
  | 'Atlantic/Azores'
  | 'Atlantic/Cape_Verde'
  | 'Europe/London'
  | 'Europe/Berlin'
  | 'Africa/Lagos'
  | 'Europe/Athens'
  | 'Africa/Cairo'
  | 'Europe/Moscow'
  | 'Asia/Riyadh'
  | 'Asia/Dubai'
  | 'Asia/Baku'
  | 'Asia/Karachi'
  | 'Asia/Tashkent'
  | 'Asia/Calcutta'
  | 'Asia/Dhaka'
  | 'Asia/Almaty'
  | 'Asia/Jakarta'
  | 'Asia/Bangkok'
  | 'Asia/Shanghai'
  | 'Asia/Singapore'
  | 'Asia/Tokyo'
  | 'Asia/Seoul'
  | 'Australia/Brisbane'
  | 'Australia/Sydney'
  | 'Pacific/Guam'
  | 'Pacific/Noumea'
  | 'Pacific/Auckland'
  | 'Pacific/Fiji';

export interface Config {
  auth: {
    users: UserAuthOperations;
  };
  blocks: {};
  collections: {
    users: User;
    media: Media;
    organisations: Organisation;
    memberships: Membership;
    'reporting-periods': ReportingPeriod;
    'metric-definitions': MetricDefinition;
    'derived-metric-definitions': DerivedMetricDefinition;
    'emission-factors': EmissionFactor;
    datapoints: Datapoint;
    evidence: Evidence;
    suppliers: Supplier;
    'internal-data-requests': InternalDataRequest;
    'materiality-assessments': MaterialityAssessment;
    reports: Report;
    'audit-logs': AuditLog;
    'benchmark-stats': BenchmarkStat;
    'compliance-obligations': ComplianceObligation;
    'payload-kv': PayloadKv;
    'payload-locked-documents': PayloadLockedDocument;
    'payload-preferences': PayloadPreference;
    'payload-migrations': PayloadMigration;
  };
  collectionsJoins: {};
  collectionsSelect: {
    users: UsersSelect<false> | UsersSelect<true>;
    media: MediaSelect<false> | MediaSelect<true>;
    organisations: OrganisationsSelect<false> | OrganisationsSelect<true>;
    memberships: MembershipsSelect<false> | MembershipsSelect<true>;
    'reporting-periods': ReportingPeriodsSelect<false> | ReportingPeriodsSelect<true>;
    'metric-definitions': MetricDefinitionsSelect<false> | MetricDefinitionsSelect<true>;
    'derived-metric-definitions': DerivedMetricDefinitionsSelect<false> | DerivedMetricDefinitionsSelect<true>;
    'emission-factors': EmissionFactorsSelect<false> | EmissionFactorsSelect<true>;
    datapoints: DatapointsSelect<false> | DatapointsSelect<true>;
    evidence: EvidenceSelect<false> | EvidenceSelect<true>;
    suppliers: SuppliersSelect<false> | SuppliersSelect<true>;
    'internal-data-requests': InternalDataRequestsSelect<false> | InternalDataRequestsSelect<true>;
    'materiality-assessments': MaterialityAssessmentsSelect<false> | MaterialityAssessmentsSelect<true>;
    reports: ReportsSelect<false> | ReportsSelect<true>;
    'audit-logs': AuditLogsSelect<false> | AuditLogsSelect<true>;
    'benchmark-stats': BenchmarkStatsSelect<false> | BenchmarkStatsSelect<true>;
    'compliance-obligations': ComplianceObligationsSelect<false> | ComplianceObligationsSelect<true>;
    'payload-kv': PayloadKvSelect<false> | PayloadKvSelect<true>;
    'payload-locked-documents': PayloadLockedDocumentsSelect<false> | PayloadLockedDocumentsSelect<true>;
    'payload-preferences': PayloadPreferencesSelect<false> | PayloadPreferencesSelect<true>;
    'payload-migrations': PayloadMigrationsSelect<false> | PayloadMigrationsSelect<true>;
  };
  db: {
    defaultIDType: string;
  };
  fallbackLocale: null;
  globals: {};
  globalsSelect: {};
  locale: null;
  widgets: {
    collections: CollectionsWidget;
  };
  user: User;
  jobs: {
    tasks: unknown;
    workflows: unknown;
  };
}
export interface UserAuthOperations {
  forgotPassword: {
    email: string;
    password: string;
  };
  login: {
    email: string;
    password: string;
  };
  registerFirstUser: {
    email: string;
    password: string;
  };
  unlock: {
    email: string;
    password: string;
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users".
 */
export interface User {
  id: string;
  /**
   * Clerk user id — set by webhook in Phase 2
   */
  clerkId?: string | null;
  firstName?: string | null;
  lastName?: string | null;
  avatarUrl?: string | null;
  lastSeenAt?: string | null;
  updatedAt: string;
  createdAt: string;
  email: string;
  resetPasswordToken?: string | null;
  resetPasswordExpiration?: string | null;
  salt?: string | null;
  hash?: string | null;
  loginAttempts?: number | null;
  lockUntil?: string | null;
  sessions?:
    | {
        id: string;
        createdAt?: string | null;
        expiresAt: string;
      }[]
    | null;
  password?: string | null;
  collection: 'users';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media".
 */
export interface Media {
  id: string;
  alt: string;
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  focalX?: number | null;
  focalY?: number | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "organisations".
 */
export interface Organisation {
  id: string;
  name: string;
  slug: string;
  type: 'company' | 'consultancy';
  /**
   * NACE code
   */
  sector: string;
  /**
   * ISO 3166-1 alpha-2
   */
  country: string;
  employeeCount?: number | null;
  revenueBand?: ('lt_2m' | '2_10m' | '10_50m' | '50_250m' | 'gt_250m') | null;
  /**
   * MM-DD, e.g. 03-31
   */
  fiscalYearEnd?: string | null;
  /**
   * Consultancy parent — one level deep only
   */
  parentOrg?: (string | null) | Organisation;
  /**
   * Legacy white-label fields — prefer settings.branding. Kept for read fallback.
   */
  brand?: {
    logo?: (string | null) | Media;
    primaryColor?: string | null;
    domain?: string | null;
  };
  settings?: {
    branding?: {
      logo?: (string | null) | Media;
      /**
       * Dashboard primary #RRGGBB → --accent
       */
      primaryColor?: string | null;
      /**
       * Dashboard secondary #RRGGBB
       */
      secondaryColor?: string | null;
      fontFamily?: ('inter_tight' | 'plus_jakarta' | 'fraunces' | 'space_grotesk') | null;
      /**
       * Org default when the user has no personal theme cookie
       */
      defaultMode?: ('light' | 'dark') | null;
      radius?: ('sharp' | 'default' | 'soft') | null;
    };
    /**
     * Custom white-label host (consultant entitlement)
     */
    domain?: string | null;
  };
  stripeCustomerId?: string | null;
  plan?: ('free' | 'pro' | 'consultant') | null;
  subscriptionStatus?: ('none' | 'active' | 'past_due' | 'canceled') | null;
  onboardedAt?: string | null;
  /**
   * First-report guided checklist — org-scoped, not localStorage.
   */
  guideProgress?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  /**
   * Opt out of anonymised sector benchmark aggregation (ToS consent).
   */
  benchmarkOptOut?: boolean | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "memberships".
 */
export interface Membership {
  id: string;
  user: string | User;
  organisation: string | Organisation;
  role: 'owner' | 'admin' | 'contributor' | 'viewer';
  status: 'active' | 'invited' | 'revoked';
  invitedBy?: (string | null) | User;
  invitedAt?: string | null;
  acceptedAt?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "reporting-periods".
 */
export interface ReportingPeriod {
  id: string;
  organisation: string | Organisation;
  label: string;
  startDate: string;
  endDate: string;
  status: 'open' | 'locked' | 'published';
  lockedAt?: string | null;
  lockedBy?: (string | null) | User;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "metric-definitions".
 */
export interface MetricDefinition {
  id: string;
  key: string;
  label: string;
  description: string;
  unit?: string | null;
  category: 'E' | 'S' | 'G';
  inputType: 'number' | 'boolean' | 'select';
  helpText: string;
  exampleSource: string;
  /**
   * Which §5 formula term this feeds
   */
  calcRole: string;
  frameworkMappings?:
    | {
        framework: 'CSRD_SET1' | 'CSRD_SIMPLIFIED' | 'BRSR' | 'VSME' | 'GRI' | 'ISSB_S1' | 'ISSB_S2' | 'EU_TAXONOMY';
        /**
         * Disclosure code (product alias: disclosureCode). Not a datapoint document id.
         */
        datapointRef: string;
        /**
         * Human disclosure name (counsel placeholder OK).
         */
        label?: string | null;
        required?: boolean | null;
        /**
         * When true, data contributes to this disclosure — never alone satisfies it.
         */
        contributionOnly?: boolean | null;
        validFrom?: string | null;
        validUntil?: string | null;
        sourceDoc?: string | null;
        sourceSheet?: string | null;
        sourceRow?: number | null;
        extractedAt?: string | null;
        id?: string | null;
      }[]
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "derived-metric-definitions".
 */
export interface DerivedMetricDefinition {
  id: string;
  key: string;
  label: string;
  description: string;
  unit: string;
  frameworkMappings?:
    | {
        framework: 'CSRD_SET1' | 'CSRD_SIMPLIFIED' | 'BRSR' | 'VSME' | 'GRI' | 'ISSB_S1' | 'ISSB_S2' | 'EU_TAXONOMY';
        /**
         * Disclosure code (product alias: disclosureCode). Not a datapoint document id.
         */
        datapointRef: string;
        /**
         * Human disclosure name (counsel placeholder OK).
         */
        label?: string | null;
        required?: boolean | null;
        /**
         * When true, data contributes to this disclosure — never alone satisfies it.
         */
        contributionOnly?: boolean | null;
        validFrom?: string | null;
        validUntil?: string | null;
        sourceDoc: string;
        sourceSheet: string;
        sourceRow: number;
        extractedAt: string;
        /**
         * Must be true to surface in product mappings
         */
        approved: boolean;
        id?: string | null;
      }[]
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "emission-factors".
 */
export interface EmissionFactor {
  id: string;
  key: string;
  label: string;
  value: number;
  /**
   * e.g. kgCO2e/kWh
   */
  unit: string;
  scope: '1' | '2' | '3';
  source: 'DEFRA' | 'EPA' | 'IEA' | 'CEA_India' | 'GHGProtocol' | 'EEA' | 'NationalInventory';
  sourceUrl: string;
  publicationYear: number;
  /**
   * ISO 3166-1 alpha-2 or GLOBAL
   */
  region: string;
  validFrom: string;
  validUntil?: string | null;
  supersededBy?: (string | null) | EmissionFactor;
  /**
   * e.g. OGL v3.0, US public domain, Government of India
   */
  licence: string;
  /**
   * Visible attribution string required by the licence (OGL etc.)
   */
  attributionText: string;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "datapoints".
 */
export interface Datapoint {
  id: string;
  organisation: string | Organisation;
  period: string | ReportingPeriod;
  metricKey: string;
  value?: number | null;
  unit?: string | null;
  quality: 'measured' | 'calculated' | 'estimated' | 'missing';
  /**
   * Where this Scope 3 figure came from. Independent of quality (measured vs estimated).
   */
  provenance?: ('supplier_primary' | 'spend_estimate' | 'manual') | null;
  /**
   * Supplier that produced this contribution, when applicable
   */
  supplier?: (string | null) | Supplier;
  /**
   * Sentinel unique-index key. Empty string = no supplier. Never null.
   */
  supplierKey?: string | null;
  /**
   * Pinned EmissionFactor id used when this value was derived
   */
  factorId?: string | null;
  evidence?: (string | Evidence)[] | null;
  source: 'manual' | 'import' | 'supplier' | 'estimate' | 'api' | 'internal_survey';
  approvalState: 'pending' | 'approved' | 'rejected';
  /**
   * Required when approvalState is rejected.
   */
  approvalReason?: string | null;
  assignedTo?: (string | null) | User;
  dueDate?: string | null;
  taskStatus?: ('open' | 'submitted' | 'approved') | null;
  enteredBy?: (string | null) | User;
  enteredAt?: string | null;
  note?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "suppliers".
 */
export interface Supplier {
  id: string;
  organisation: string | Organisation;
  name: string;
  contactEmail: string;
  category: 'purchased_goods' | 'capital_goods' | 'transport' | 'waste' | 'business_travel' | 'other';
  annualSpend?: number | null;
  /**
   * Reporting period this request token is bound to
   */
  requestPeriod?: (string | null) | ReportingPeriod;
  requestToken?: string | null;
  requestStatus?: ('not_sent' | 'sent' | 'opened' | 'submitted' | 'declined') | null;
  sentAt?: string | null;
  requestExpiresAt?: string | null;
  respondedAt?: string | null;
  lastReminderAt?: string | null;
  submittedData?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  reminderCount?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "evidence".
 */
export interface Evidence {
  id: string;
  organisation: string | Organisation;
  file: string | Media;
  filename: string;
  mimeType?: string | null;
  size?: number | null;
  sha256: string;
  uploadedBy?: (string | null) | User;
  uploadedAt: string;
  /**
   * Start of the period this evidence covers (for assurance freshness).
   */
  coverageStart?: string | null;
  /**
   * End of the period this evidence covers (for assurance freshness).
   */
  coverageEnd?: string | null;
  linkedDatapoints?: (string | Datapoint)[] | null;
  /**
   * Why this document proves the figure — shown to auditors and reviewers.
   */
  whyNote?: string | null;
  extractedData?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  /**
   * OCR is not productized; new uploads should set skipped until a worker ships.
   */
  ocrStatus?: ('pending' | 'done' | 'failed' | 'skipped') | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "internal-data-requests".
 */
export interface InternalDataRequest {
  id: string;
  organisation: string | Organisation;
  period: string | ReportingPeriod;
  title: string;
  assignee: string | User;
  metricKeys: {
    key: string;
    id?: string | null;
  }[];
  requestStatus?: ('not_sent' | 'sent' | 'opened' | 'submitted') | null;
  dueDate?: string | null;
  sentAt?: string | null;
  openedAt?: string | null;
  submittedAt?: string | null;
  lastReminderAt?: string | null;
  reminderCount?: number | null;
  createdBy?: (string | null) | User;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "materiality-assessments".
 */
export interface MaterialityAssessment {
  id: string;
  organisation: string | Organisation;
  period: string | ReportingPeriod;
  status: 'draft' | 'final';
  topics?:
    | {
        esrsTopic: string;
        impactSeverity?: number | null;
        impactScope?: number | null;
        impactIrremediability?: number | null;
        financialMagnitude?: number | null;
        financialLikelihood?: number | null;
        impactScore: number;
        financialScore: number;
        rationale?: string | null;
        /**
         * Auditor trail — sector starting position accepted vs actively changed.
         */
        origin?: ('suggested' | 'adjusted') | null;
        decidedBy?: (string | null) | User;
        decidedAt?: string | null;
        id?: string | null;
      }[]
    | null;
  matrixSnapshot?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  narrative?: string | null;
  finalisedAt?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "reports".
 */
export interface Report {
  id: string;
  organisation: string | Organisation;
  period: string | ReportingPeriod;
  framework: 'CSRD_SET1' | 'CSRD_SIMPLIFIED' | 'BRSR' | 'VSME' | 'GRI' | 'CUSTOM';
  version: number;
  status: 'draft' | 'published';
  scores?: {
    overall?: number | null;
    e?: number | null;
    s?: number | null;
    g?: number | null;
  };
  emissions?: {
    scope1?: number | null;
    scope2?: number | null;
    scope3?: number | null;
  };
  dataQualityPct?: number | null;
  factorVersionsUsed?: (string | EmissionFactor)[] | null;
  /**
   * Immutable publish payload — never mutate after published
   */
  snapshot?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  pdfUrl?: string | null;
  shareToken?: string | null;
  /**
   * Token for read-only /a/[token] Assurance Room (no Membership role).
   */
  assuranceToken?: string | null;
  shareExpiresAt?: string | null;
  viewCount?: number | null;
  publishedAt?: string | null;
  publishedBy?: (string | null) | User;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "audit-logs".
 */
export interface AuditLog {
  id: string;
  organisation: string | Organisation;
  /**
   * Optional — public supplier token submits may omit actor; reconstruct from after.tokenId / supplierId
   */
  actor?: (string | null) | User;
  action: string;
  entityType: string;
  entityId: string;
  before?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  after?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  ip?: string | null;
  userAgent?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "benchmark-stats".
 */
export interface BenchmarkStat {
  id: string;
  sector: string;
  sizeBand: string;
  metricKey: string;
  period: string;
  p25: number;
  p50: number;
  p75: number;
  cohortSize: number;
  /**
   * As-of timestamp for this cohort row.
   */
  computedAt?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "compliance-obligations".
 */
export interface ComplianceObligation {
  id: string;
  organisation: string | Organisation;
  wave: '1' | '2' | '3' | 'brsr_listed' | 'brsr_supply' | 'other';
  /**
   * ISO country or region code, e.g. EU, IN, GB
   */
  jurisdiction: string;
  standardVersion: 'CSRD_SET1' | 'CSRD_SIMPLIFIED' | 'BRSR' | 'VSME' | 'GRI';
  /**
   * e.g. "FY2025" or "2025-26"
   */
  firstReportingFY: string;
  /**
   * Countdown the Compliance Runway displays. Leave empty for voluntary / not in mandatory scope — never invent a date.
   */
  filingDeadline?: string | null;
  notes?: string | null;
  /**
   * Plain-language why this obligation was derived or overridden
   */
  derivationReason?: string | null;
  /**
   * needs_confirmation surfaces a gentle Runway prompt; derived is still confirmable, never legal advice
   */
  confidence?: ('derived' | 'needs_confirmation') | null;
  /**
   * Manual overrides are sticky on baseline change — do not silently overwrite
   */
  source?: ('engine' | 'manual') | null;
  /**
   * When an Owner/Admin confirmed or overrode the obligation
   */
  confirmedAt?: string | null;
  /**
   * Baseline snapshot used at last engine derivation
   */
  derivedInputs?: {
    country?: string | null;
    headcount?: number | null;
    revenueBand?: ('lt_2m' | '2_10m' | '10_50m' | '50_250m' | 'gt_250m') | null;
    asOf?: string | null;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv".
 */
export interface PayloadKv {
  id: string;
  key: string;
  data:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents".
 */
export interface PayloadLockedDocument {
  id: string;
  document?:
    | ({
        relationTo: 'users';
        value: string | User;
      } | null)
    | ({
        relationTo: 'media';
        value: string | Media;
      } | null)
    | ({
        relationTo: 'organisations';
        value: string | Organisation;
      } | null)
    | ({
        relationTo: 'memberships';
        value: string | Membership;
      } | null)
    | ({
        relationTo: 'reporting-periods';
        value: string | ReportingPeriod;
      } | null)
    | ({
        relationTo: 'metric-definitions';
        value: string | MetricDefinition;
      } | null)
    | ({
        relationTo: 'derived-metric-definitions';
        value: string | DerivedMetricDefinition;
      } | null)
    | ({
        relationTo: 'emission-factors';
        value: string | EmissionFactor;
      } | null)
    | ({
        relationTo: 'datapoints';
        value: string | Datapoint;
      } | null)
    | ({
        relationTo: 'evidence';
        value: string | Evidence;
      } | null)
    | ({
        relationTo: 'suppliers';
        value: string | Supplier;
      } | null)
    | ({
        relationTo: 'internal-data-requests';
        value: string | InternalDataRequest;
      } | null)
    | ({
        relationTo: 'materiality-assessments';
        value: string | MaterialityAssessment;
      } | null)
    | ({
        relationTo: 'reports';
        value: string | Report;
      } | null)
    | ({
        relationTo: 'audit-logs';
        value: string | AuditLog;
      } | null)
    | ({
        relationTo: 'benchmark-stats';
        value: string | BenchmarkStat;
      } | null)
    | ({
        relationTo: 'compliance-obligations';
        value: string | ComplianceObligation;
      } | null);
  globalSlug?: string | null;
  user: {
    relationTo: 'users';
    value: string | User;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences".
 */
export interface PayloadPreference {
  id: string;
  user: {
    relationTo: 'users';
    value: string | User;
  };
  key?: string | null;
  value?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations".
 */
export interface PayloadMigration {
  id: string;
  name?: string | null;
  batch?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users_select".
 */
export interface UsersSelect<T extends boolean = true> {
  clerkId?: T;
  firstName?: T;
  lastName?: T;
  avatarUrl?: T;
  lastSeenAt?: T;
  updatedAt?: T;
  createdAt?: T;
  email?: T;
  resetPasswordToken?: T;
  resetPasswordExpiration?: T;
  salt?: T;
  hash?: T;
  loginAttempts?: T;
  lockUntil?: T;
  sessions?:
    | T
    | {
        id?: T;
        createdAt?: T;
        expiresAt?: T;
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media_select".
 */
export interface MediaSelect<T extends boolean = true> {
  alt?: T;
  updatedAt?: T;
  createdAt?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
  focalX?: T;
  focalY?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "organisations_select".
 */
export interface OrganisationsSelect<T extends boolean = true> {
  name?: T;
  slug?: T;
  type?: T;
  sector?: T;
  country?: T;
  employeeCount?: T;
  revenueBand?: T;
  fiscalYearEnd?: T;
  parentOrg?: T;
  brand?:
    | T
    | {
        logo?: T;
        primaryColor?: T;
        domain?: T;
      };
  settings?:
    | T
    | {
        branding?:
          | T
          | {
              logo?: T;
              primaryColor?: T;
              secondaryColor?: T;
              fontFamily?: T;
              defaultMode?: T;
              radius?: T;
            };
        domain?: T;
      };
  stripeCustomerId?: T;
  plan?: T;
  subscriptionStatus?: T;
  onboardedAt?: T;
  guideProgress?: T;
  benchmarkOptOut?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "memberships_select".
 */
export interface MembershipsSelect<T extends boolean = true> {
  user?: T;
  organisation?: T;
  role?: T;
  status?: T;
  invitedBy?: T;
  invitedAt?: T;
  acceptedAt?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "reporting-periods_select".
 */
export interface ReportingPeriodsSelect<T extends boolean = true> {
  organisation?: T;
  label?: T;
  startDate?: T;
  endDate?: T;
  status?: T;
  lockedAt?: T;
  lockedBy?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "metric-definitions_select".
 */
export interface MetricDefinitionsSelect<T extends boolean = true> {
  key?: T;
  label?: T;
  description?: T;
  unit?: T;
  category?: T;
  inputType?: T;
  helpText?: T;
  exampleSource?: T;
  calcRole?: T;
  frameworkMappings?:
    | T
    | {
        framework?: T;
        datapointRef?: T;
        label?: T;
        required?: T;
        contributionOnly?: T;
        validFrom?: T;
        validUntil?: T;
        sourceDoc?: T;
        sourceSheet?: T;
        sourceRow?: T;
        extractedAt?: T;
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "derived-metric-definitions_select".
 */
export interface DerivedMetricDefinitionsSelect<T extends boolean = true> {
  key?: T;
  label?: T;
  description?: T;
  unit?: T;
  frameworkMappings?:
    | T
    | {
        framework?: T;
        datapointRef?: T;
        label?: T;
        required?: T;
        contributionOnly?: T;
        validFrom?: T;
        validUntil?: T;
        sourceDoc?: T;
        sourceSheet?: T;
        sourceRow?: T;
        extractedAt?: T;
        approved?: T;
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "emission-factors_select".
 */
export interface EmissionFactorsSelect<T extends boolean = true> {
  key?: T;
  label?: T;
  value?: T;
  unit?: T;
  scope?: T;
  source?: T;
  sourceUrl?: T;
  publicationYear?: T;
  region?: T;
  validFrom?: T;
  validUntil?: T;
  supersededBy?: T;
  licence?: T;
  attributionText?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "datapoints_select".
 */
export interface DatapointsSelect<T extends boolean = true> {
  organisation?: T;
  period?: T;
  metricKey?: T;
  value?: T;
  unit?: T;
  quality?: T;
  provenance?: T;
  supplier?: T;
  supplierKey?: T;
  factorId?: T;
  evidence?: T;
  source?: T;
  approvalState?: T;
  approvalReason?: T;
  assignedTo?: T;
  dueDate?: T;
  taskStatus?: T;
  enteredBy?: T;
  enteredAt?: T;
  note?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "evidence_select".
 */
export interface EvidenceSelect<T extends boolean = true> {
  organisation?: T;
  file?: T;
  filename?: T;
  mimeType?: T;
  size?: T;
  sha256?: T;
  uploadedBy?: T;
  uploadedAt?: T;
  coverageStart?: T;
  coverageEnd?: T;
  linkedDatapoints?: T;
  whyNote?: T;
  extractedData?: T;
  ocrStatus?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "suppliers_select".
 */
export interface SuppliersSelect<T extends boolean = true> {
  organisation?: T;
  name?: T;
  contactEmail?: T;
  category?: T;
  annualSpend?: T;
  requestPeriod?: T;
  requestToken?: T;
  requestStatus?: T;
  sentAt?: T;
  requestExpiresAt?: T;
  respondedAt?: T;
  lastReminderAt?: T;
  submittedData?: T;
  reminderCount?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "internal-data-requests_select".
 */
export interface InternalDataRequestsSelect<T extends boolean = true> {
  organisation?: T;
  period?: T;
  title?: T;
  assignee?: T;
  metricKeys?:
    | T
    | {
        key?: T;
        id?: T;
      };
  requestStatus?: T;
  dueDate?: T;
  sentAt?: T;
  openedAt?: T;
  submittedAt?: T;
  lastReminderAt?: T;
  reminderCount?: T;
  createdBy?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "materiality-assessments_select".
 */
export interface MaterialityAssessmentsSelect<T extends boolean = true> {
  organisation?: T;
  period?: T;
  status?: T;
  topics?:
    | T
    | {
        esrsTopic?: T;
        impactSeverity?: T;
        impactScope?: T;
        impactIrremediability?: T;
        financialMagnitude?: T;
        financialLikelihood?: T;
        impactScore?: T;
        financialScore?: T;
        rationale?: T;
        origin?: T;
        decidedBy?: T;
        decidedAt?: T;
        id?: T;
      };
  matrixSnapshot?: T;
  narrative?: T;
  finalisedAt?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "reports_select".
 */
export interface ReportsSelect<T extends boolean = true> {
  organisation?: T;
  period?: T;
  framework?: T;
  version?: T;
  status?: T;
  scores?:
    | T
    | {
        overall?: T;
        e?: T;
        s?: T;
        g?: T;
      };
  emissions?:
    | T
    | {
        scope1?: T;
        scope2?: T;
        scope3?: T;
      };
  dataQualityPct?: T;
  factorVersionsUsed?: T;
  snapshot?: T;
  pdfUrl?: T;
  shareToken?: T;
  assuranceToken?: T;
  shareExpiresAt?: T;
  viewCount?: T;
  publishedAt?: T;
  publishedBy?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "audit-logs_select".
 */
export interface AuditLogsSelect<T extends boolean = true> {
  organisation?: T;
  actor?: T;
  action?: T;
  entityType?: T;
  entityId?: T;
  before?: T;
  after?: T;
  ip?: T;
  userAgent?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "benchmark-stats_select".
 */
export interface BenchmarkStatsSelect<T extends boolean = true> {
  sector?: T;
  sizeBand?: T;
  metricKey?: T;
  period?: T;
  p25?: T;
  p50?: T;
  p75?: T;
  cohortSize?: T;
  computedAt?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "compliance-obligations_select".
 */
export interface ComplianceObligationsSelect<T extends boolean = true> {
  organisation?: T;
  wave?: T;
  jurisdiction?: T;
  standardVersion?: T;
  firstReportingFY?: T;
  filingDeadline?: T;
  notes?: T;
  derivationReason?: T;
  confidence?: T;
  source?: T;
  confirmedAt?: T;
  derivedInputs?:
    | T
    | {
        country?: T;
        headcount?: T;
        revenueBand?: T;
        asOf?: T;
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv_select".
 */
export interface PayloadKvSelect<T extends boolean = true> {
  key?: T;
  data?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents_select".
 */
export interface PayloadLockedDocumentsSelect<T extends boolean = true> {
  document?: T;
  globalSlug?: T;
  user?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences_select".
 */
export interface PayloadPreferencesSelect<T extends boolean = true> {
  user?: T;
  key?: T;
  value?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations_select".
 */
export interface PayloadMigrationsSelect<T extends boolean = true> {
  name?: T;
  batch?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "collections_widget".
 */
export interface CollectionsWidget {
  data?: {
    [k: string]: unknown;
  };
  width: 'full';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "auth".
 */
export interface Auth {
  [k: string]: unknown;
}


declare module 'payload' {
  export interface GeneratedTypes extends Config {}
}